title: Liza Aulia Siregar
email: lizaauliasiregar07@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Saya mahasiswi Politeknik Negeri Lhokseumawe jurusan TIK yang sedang belajar di prodi Teknik Informatika. Saya lahir pada 11 Mei 2006.
url: 'https://github.com/lizaauliasiregar/lizaauliasiregar.github.io'

plugins:
 - jekyll-feed
 - jekyll-sitemap
 - jekyll-seo-tag